
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  1 2025 14:57:26 IST (Mar  1 2025 09:27:26 UTC)

// Verification Directory fv/q_gate 

module q_gate(a, b, c, q);
  input a, b, c;
  output q;
  wire a, b, c;
  wire q;
  wire n_0;
  AND2X2 g41__2398(.A (c), .B (n_0), .Y (q));
  NOR2XL g42__5107(.A (b), .B (a), .Y (n_0));
endmodule

