
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 22 2025 14:49:52 IST (Mar 22 2025 09:19:52 UTC)

// Verification Directory fv/vending_machine 

module vending_machine(clk, rst, in, out, change, c_state, n_state);
  input clk, rst;
  input [1:0] in;
  output out;
  output [1:0] change, c_state, n_state;
  wire clk, rst;
  wire [1:0] in;
  wire out;
  wire [1:0] change, c_state, n_state;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26;
  DFFQX1 out_reg(.CK (clk), .D (n_26), .Q (out));
  DFFQX1 \change_reg[1] (.CK (clk), .D (n_25), .Q (change[1]));
  DFFQX1 \change_reg[0] (.CK (clk), .D (n_24), .Q (change[0]));
  OAI211XL g930__2398(.A0 (n_8), .A1 (n_13), .B0 (n_15), .C0 (n_23), .Y
       (n_26));
  DFFQX1 \n_state_reg[1] (.CK (clk), .D (n_21), .Q (n_state[1]));
  INVXL g933(.A (n_22), .Y (n_25));
  NAND2XL g934__5107(.A (n_23), .B (n_18), .Y (n_24));
  DFFQX1 \n_state_reg[0] (.CK (clk), .D (n_14), .Q (n_state[0]));
  AOI32XL g935__6260(.A0 (n_16), .A1 (n_17), .A2 (change[1]), .B0
       (n_19), .B1 (n_20), .Y (n_22));
  OAI22XL g932__4319(.A0 (n_10), .A1 (n_20), .B0 (n_12), .B1 (n_7), .Y
       (n_21));
  NAND2XL g941__8428(.A (in[1]), .B (n_19), .Y (n_23));
  NAND3XL g937__5526(.A (n_17), .B (change[0]), .C (n_16), .Y (n_18));
  AOI21XL g938__6783(.A0 (n_6), .A1 (out), .B0 (n_11), .Y (n_15));
  OAI21XL g942__3680(.A0 (n_9), .A1 (n_13), .B0 (n_5), .Y (n_14));
  NOR3X1 g949__1617(.A (in[0]), .B (n_state[0]), .C (n_12), .Y (n_19));
  NOR3X1 g939__2802(.A (n_4), .B (n_state[0]), .C (n_12), .Y (n_11));
  DFFQXL \c_state_reg[0] (.CK (clk), .D (n_2), .Q (c_state[0]));
  AOI22XL g943__1705(.A0 (n_9), .A1 (n_3), .B0 (rst), .B1 (n_0), .Y
       (n_10));
  MXI2XL g944__5122(.A (out), .B (in[1]), .S0 (n_9), .Y (n_8));
  NOR2XL g947__8246(.A (n_6), .B (n_state[0]), .Y (n_7));
  NAND2BXL g948__7098(.AN (n_4), .B (n_12), .Y (n_5));
  OAI21X1 g940__6131(.A0 (n_3), .A1 (n_9), .B0 (n_1), .Y (n_16));
  DFFTRXL \c_state_reg[1] (.CK (clk), .D (n_state[1]), .RN (n_17), .Q
       (c_state[1]), .QN (UNCONNECTED));
  NOR2XL g954__1881(.A (rst), .B (n_3), .Y (n_2));
  NAND2XL g952__5115(.A (n_17), .B (n_state[1]), .Y (n_12));
  NAND2XL g955__7482(.A (n_17), .B (n_state[0]), .Y (n_13));
  CLKINVX1 g950(.A (n_1), .Y (n_6));
  NAND2XL g956__4733(.A (in[0]), .B (n_20), .Y (n_4));
  NOR2XL g953__6161(.A (in[0]), .B (n_state[1]), .Y (n_9));
  NAND2XL g951__9315(.A (in[0]), .B (in[1]), .Y (n_1));
  CLKINVX1 g958(.A (in[1]), .Y (n_20));
  CLKINVX1 g960(.A (n_state[0]), .Y (n_3));
  CLKINVX1 g957(.A (in[0]), .Y (n_0));
  CLKINVX1 g959(.A (rst), .Y (n_17));
endmodule

