
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 16:13:02 IST (Feb 22 2025 10:43:02 UTC)

// Verification Directory fv/fulladder 

module fulladder(a, b, c, y, cout);
  input a, b, c;
  output y, cout;
  wire a, b, c;
  wire y, cout;
  ADDFX2 g85__2398(.A (a), .B (c), .CI (b), .CO (cout), .S (y));
endmodule

