
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2025 16:23:14 IST (Feb 18 2025 10:53:14 UTC)

// Verification Directory fv/master_slave_jk_flipflop 

module master_slave_jk_flipflop(J, K, clk, rst, Q, Q_bar);
  input J, K, clk, rst;
  output Q, Q_bar;
  wire J, K, clk, rst;
  wire Q, Q_bar;
  wire master_Q, n_0, n_1;
  SDFFRHQX1 master_Q_reg(.RN (n_1), .CK (clk), .D (J), .SI (n_0), .SE
       (master_Q), .Q (master_Q));
  DFFNSRXL Q_reg(.RN (n_1), .SN (1'b1), .CKN (clk), .D (master_Q), .Q
       (Q), .QN (Q_bar));
  INVXL g42(.A (rst), .Y (n_1));
  INVXL g41(.A (K), .Y (n_0));
endmodule

