
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 15:10:23 IST (Feb 22 2025 09:40:23 UTC)

// Verification Directory fv/fulladder 

module fulladder(a, b, c, y, cout);
  input a, b, c;
  output y, cout;
  wire a, b, c;
  wire y, cout;
  ADDFXL g87__2398(.A (a), .B (b), .CI (c), .CO (cout), .S (y));
endmodule

