
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  1 2025 14:45:21 IST (Mar  1 2025 09:15:21 UTC)

// Verification Directory fv/q 

module q(a, b, c, q);
  input a, b, c;
  output q;
  wire a, b, c;
  wire q;
  wire n_0;
  AND2X2 g59__2398(.A (c), .B (n_0), .Y (q));
  NOR2XL g60__5107(.A (b), .B (a), .Y (n_0));
endmodule

