
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2025 16:09:30 IST (Feb 18 2025 10:39:30 UTC)

// Verification Directory fv/universal_shift_register 

module universal_shift_register(clk, reset, mode, data_in, serial_in,
     data_out);
  input clk, reset, serial_in;
  input [1:0] mode;
  input [3:0] data_in;
  output [3:0] data_out;
  wire clk, reset, serial_in;
  wire [1:0] mode;
  wire [3:0] data_in;
  wire [3:0] data_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17;
  DFFQX1 \data_out_reg[0] (.CK (clk), .D (n_17), .Q (data_out[0]));
  DFFQX1 \data_out_reg[1] (.CK (clk), .D (n_14), .Q (data_out[1]));
  DFFQX1 \data_out_reg[3] (.CK (clk), .D (n_16), .Q (data_out[3]));
  DFFQX1 \data_out_reg[2] (.CK (clk), .D (n_15), .Q (data_out[2]));
  NAND2XL g462__2398(.A (n_8), .B (n_7), .Y (n_17));
  NAND2XL g461__5107(.A (n_11), .B (n_3), .Y (n_16));
  NAND2XL g463__6260(.A (n_4), .B (n_2), .Y (n_15));
  NAND2XL g464__4319(.A (n_12), .B (n_13), .Y (n_14));
  AOI22X1 g466__8428(.A0 (n_10), .A1 (data_out[1]), .B0 (n_6), .B1
       (data_out[0]), .Y (n_13));
  AOI22X1 g472__5526(.A0 (n_9), .A1 (data_out[2]), .B0 (data_in[1]),
       .B1 (n_5), .Y (n_12));
  AOI22X1 g471__6783(.A0 (n_10), .A1 (data_out[3]), .B0 (serial_in),
       .B1 (n_9), .Y (n_11));
  AOI22X1 g467__3680(.A0 (n_10), .A1 (data_out[0]), .B0 (n_9), .B1
       (data_out[1]), .Y (n_8));
  AOI22XL g470__1617(.A0 (n_6), .A1 (serial_in), .B0 (n_5), .B1
       (data_in[0]), .Y (n_7));
  AOI22X1 g469__2802(.A0 (n_9), .A1 (data_out[3]), .B0 (data_in[2]),
       .B1 (n_5), .Y (n_4));
  AOI22X1 g468__1705(.A0 (n_6), .A1 (data_out[2]), .B0 (data_in[3]),
       .B1 (n_5), .Y (n_3));
  AOI22X1 g465__5122(.A0 (n_10), .A1 (data_out[2]), .B0 (n_6), .B1
       (data_out[1]), .Y (n_2));
  AND2X1 g474__8246(.A (mode[0]), .B (n_1), .Y (n_9));
  NOR2BXL g475__7098(.AN (n_1), .B (mode[0]), .Y (n_10));
  NOR2XL g476__6131(.A (mode[0]), .B (n_0), .Y (n_6));
  NOR2BXL g473__1881(.AN (mode[0]), .B (n_0), .Y (n_5));
  NOR2XL g477__5115(.A (mode[1]), .B (reset), .Y (n_1));
  NAND2BXL g478__7482(.AN (reset), .B (mode[1]), .Y (n_0));
endmodule

