
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  1 2025 14:37:46 IST (Mar  1 2025 09:07:46 UTC)

// Verification Directory fv/q 

module q(a, b, c, q);
  input a, b, c;
  output q;
  wire a, b, c;
  wire q;
  NOR3BXL g59__2398(.AN (c), .B (b), .C (a), .Y (q));
endmodule

