
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 25 2025 14:48:30 IST (Mar 25 2025 09:18:30 UTC)

// Verification Directory fv/vending_machine 

module vending_machine(clk, rst, in, out, change, c_state, n_state);
  input clk, rst;
  input [1:0] in;
  output out;
  output [1:0] change, c_state, n_state;
  wire clk, rst;
  wire [1:0] in;
  wire out;
  wire [1:0] change, c_state, n_state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15;
  assign n_state[0] = 1'b0;
  assign n_state[1] = 1'b0;
  assign change[0] = 1'b0;
  assign change[1] = 1'b0;
  assign out = 1'b0;
  TLATXL \n_state_reg[1]70 (.G (n_15), .D (n_14), .Q (n_state[1]), .QN
       (UNCONNECTED));
  TLATXL \change_reg[0]67 (.G (n_15), .D (n_11), .Q (change[0]), .QN
       (UNCONNECTED0));
  TLATXL \change_reg[1]68 (.G (n_15), .D (n_9), .Q (change[1]), .QN
       (UNCONNECTED1));
  INVXL g672(.A (n_13), .Y (n_14));
  TLATXL \n_state_reg[0]69 (.G (n_15), .D (n_12), .Q (n_state[0]), .QN
       (UNCONNECTED2));
  TLATXL out_reg66(.G (n_15), .D (n_10), .Q (out), .QN (UNCONNECTED3));
  AOI32XL g675__2398(.A0 (n_3), .A1 (in[0]), .A2 (n_1), .B0 (n_4), .B1
       (in[1]), .Y (n_13));
  AND3XL g676__5107(.A (in[0]), .B (n_1), .C (n_4), .Y (n_12));
  NAND3XL g677__6260(.A (in[0]), .B (in[1]), .C (n_2), .Y (n_15));
  AO22X1 g678__4319(.A0 (n_5), .A1 (n_3), .B0 (in[1]), .B1 (n_6), .Y
       (n_11));
  OAI21XL g679__8428(.A0 (n_7), .A1 (n_5), .B0 (n_8), .Y (n_10));
  NOR2BXL g680__5526(.AN (n_5), .B (n_7), .Y (n_9));
  NAND2XL g681__6783(.A (in[1]), .B (n_3), .Y (n_8));
  INVXL g682(.A (n_7), .Y (n_6));
  NAND2BXL g683__3680(.AN (c_state[0]), .B (c_state[1]), .Y (n_7));
  NOR2XL g684__1617(.A (in[1]), .B (in[0]), .Y (n_5));
  NAND2XL g685__2802(.A (c_state[1]), .B (c_state[0]), .Y (n_2));
  NOR2XL g686__1705(.A (c_state[1]), .B (c_state[0]), .Y (n_4));
  NOR2BXL g687__5122(.AN (c_state[0]), .B (c_state[1]), .Y (n_3));
  CLKINVX1 g688(.A (in[1]), .Y (n_1));
  DFFRHQX1 \c_state_reg[0] (.RN (n_0), .CK (clk), .D (n_state[0]), .Q
       (c_state[0]));
  DFFRHQX1 \c_state_reg[1] (.RN (n_0), .CK (clk), .D (n_state[1]), .Q
       (c_state[1]));
  INVXL g531(.A (rst), .Y (n_0));
endmodule

