
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  1 2025 14:27:47 IST (Mar  1 2025 08:57:47 UTC)

// Verification Directory fv/fa 

module fa(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFX2 g85__2398(.A (a), .B (cin), .CI (b), .CO (cout), .S (sum));
endmodule

