
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2025 16:31:54 IST (Feb 18 2025 11:01:54 UTC)

// Verification Directory fv/mod8_counter 

module mod8_counter(clk, reset, count);
  input clk, reset;
  output [2:0] count;
  wire clk, reset;
  wire [2:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  DFFQX1 \count_reg[2] (.CK (clk), .D (n_6), .Q (count[2]));
  DFFQX1 \count_reg[1] (.CK (clk), .D (n_5), .Q (count[1]));
  NOR2XL g57__2398(.A (reset), .B (n_4), .Y (n_6));
  NOR2XL g61__5107(.A (reset), .B (n_3), .Y (n_5));
  AOI21XL g59__6260(.A0 (count[2]), .A1 (n_2), .B0 (n_1), .Y (n_4));
  DFFQX1 \count_reg[0] (.CK (clk), .D (n_0), .Q (count[0]));
  OAI21XL g63__4319(.A0 (count[1]), .A1 (count[0]), .B0 (n_2), .Y
       (n_3));
  NOR2XL g60__8428(.A (count[2]), .B (n_2), .Y (n_1));
  NAND2XL g64__5526(.A (count[0]), .B (count[1]), .Y (n_2));
  NOR2XL g65__6783(.A (reset), .B (count[0]), .Y (n_0));
endmodule

