
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 18 2025 15:04:34 IST (Feb 18 2025 09:34:34 UTC)

// Verification Directory fv/pipo_seq 

module pipo_seq(clk, rst, pi, po);
  input clk, rst;
  input [3:0] pi;
  output [3:0] po;
  wire clk, rst;
  wire [3:0] pi;
  wire [3:0] po;
  wire n_0, n_1, n_2, n_3;
  DFFQXL \po_reg[3] (.CK (clk), .D (n_3), .Q (po[3]));
  DFFQXL \po_reg[2] (.CK (clk), .D (n_0), .Q (po[2]));
  DFFQXL \po_reg[0] (.CK (clk), .D (n_1), .Q (po[0]));
  DFFQXL \po_reg[1] (.CK (clk), .D (n_2), .Q (po[1]));
  NOR2BXL g7__2398(.AN (pi[3]), .B (rst), .Y (n_3));
  NOR2BXL g9__5107(.AN (pi[1]), .B (rst), .Y (n_2));
  NOR2BXL g8__6260(.AN (pi[0]), .B (rst), .Y (n_1));
  NOR2BXL g10__4319(.AN (pi[2]), .B (rst), .Y (n_0));
endmodule

