
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 22 2025 15:48:58 IST (Feb 22 2025 10:18:58 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, m, count);
  input clk, rst, m;
  output [3:0] count;
  wire clk, rst, m;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10;
  INVXL g264(.A (n_9), .Y (n_10));
  MXI2XL g263__2398(.A (n_6), .B (n_7), .S0 (count[2]), .Y (n_8));
  NAND2XL g265__5107(.A (n_7), .B (n_6), .Y (n_9));
  NAND2XL g266__6260(.A (n_3), .B (n_5), .Y (n_6));
  NAND2BX1 g268__4319(.AN (n_3), .B (n_2), .Y (n_4));
  NAND2BX1 g267__8428(.AN (n_2), .B (m), .Y (n_7));
  NAND2XL g270__5526(.A (count[0]), .B (count[1]), .Y (n_2));
  NOR2XL g271__6783(.A (count[0]), .B (count[1]), .Y (n_3));
  CLKINVX1 g272(.A (count[3]), .Y (n_1));
  CLKINVX1 g273(.A (m), .Y (n_5));
  DFFRX2 \count_reg[0] (.RN (rst), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
  SDFFRHQX2 \count_reg[3] (.RN (rst), .CK (clk), .D (count[3]), .SI
       (n_1), .SE (n_8), .Q (count[3]));
  SDFFRHQX2 \count_reg[2] (.RN (rst), .CK (clk), .D (n_9), .SI (n_10),
       .SE (count[2]), .Q (count[2]));
  SDFFRHQX2 \count_reg[1] (.RN (rst), .CK (clk), .D (m), .SI (n_5), .SE
       (n_4), .Q (count[1]));
endmodule

